### ISSUE TITLE
Sources shows the source in .esm-cache and not the actual source.

### ISSUE THREAD

**Issue by jdalton** [asfktz/hack#2]
While the filename of the source file is correct the source code displayed in the source tab is that of the compiled source (behind the scenes) and not the actual source file.

<img width="616" src="https://user-images.githubusercontent.com/4303/30681514-97b7b38e-9e5a-11e7-814c-87bfc279a833.png">

**Comment by asfktz** [comment]
Hi, @jdalton
Thanks for the feedback!

I'm truly honored by your presence here (:

> While the filename of the source file is correct the source code displayed in the source tab is that of the compiled source (behind the scenes) and not the actual source file.

Hmm.. interesting.

I was able to reproduce it outside the context of the project, using node's `--inspect` flag.

Is there a source-map flag that I need to pass to `@std/esm`?

**Steps to reproduce with node's --inspect:**
1. Clone: https://gist.github.com/anonymous/c925acffa146dbf7543406e0810a4bf0
2. `npm i`
3. `node --inspect --inspect-brk -r @std/esm index.mjs`
4. Open chrome and go to: `chrome://inspect/#devices`
5. Click `Open dedicated DevTools for Node`

Results:
![screen shot 2017-09-21 at 15 28 49](https://user-images.githubusercontent.com/199747/30695665-9b1d2432-9ee1-11e7-950f-cff627a7f43d.png)

**Comment by jdalton** [comment]
Ya, I was thinking about that. Our changes are inline so line numbers are preserved. I'll look into generating a basic inline map.
