### ISSUE TITLE
Detect devtools-playground?

### ISSUE THREAD

**Issue by jdalton** [asfktz/hack#3]
Is there a way to detect if code is running with devtools-playground?
I'm wanting to add a bit more debug info (source maps) in those cases.

I've already got detection for the builtin `--inspect` and friends flags.
Related to https://github.com/node-inspector/node-inspector/issues/1021.

**Comment by jdalton** [comment]
Related to https://github.com/node-inspector/node-inspector/issues/1021.

**Comment by asfktz** [comment]
The only place in the codebase I refer to `@std/esm` is in `./renderer.js`:

https://github.com/asfktz/devtools-playground/blob/336b1dfb139085a2c7a2dfd3b68668c81ea949af/renderer.js#L1-L19

So I can call `@std/esm` with another option, something like:

```js
require('@std/esm')(module, {
    cjs: true,
    esm: 'js',
    sourcemap: true
});
```

What do you think?

Btw, the options are currently hardcoded.
I'm searching for an elegant way to override the defaults.

I can let the user pass in something like that:
`devtools --esm='{ "cjs": true, "esm": "js", "await": true }'`

But it doesn't feel right. Do you have an idea?

**Comment by jdalton** [comment]
I'll add a `sourceMap` option *(you can also use `sourcemap` all-lower)*!

For options `@std/esm` can use the ones in the devs package options. You could have an option that is like `--esm inherit` that then just skips passing the hardcoded option *(in which case `@std/esm` will use the devs package options)*

**Comment by jdalton** [comment]
`@std/esm` v0.11.0 is released :tada:

You can use `sourceMap: true` to enable source maps for the dev console.

**Comment by asfktz** [comment]
@jdalton that is so awesome, thanks!

It works like a charm:

![screen shot 2017-09-27 at 21 06 41](https://user-images.githubusercontent.com/199747/30929702-ee4cd608-a3c7-11e7-9e99-0f2d40d7b40e.png)
Just released a new version with it ✨

**Comment by jdalton** [comment]
YES! 👏  Thank you!

When you get a chance could you update the animated gif too *(I know it's a pain)* but that would be a nice touch.

**Comment by jdalton** [comment]
When you get a chance could you update the animated gif too (I know it's a pain) but that would be a nice touch.

**Comment by asfktz** [comment]
I will (:
